### ISSUE TITLE
Cannot find the star images

### ISSUE THREAD

**Issue by clayne11** [andreivolt/meteor-autoform-raty#1]
I am trying to use your package and when I load the page with a rating star on it it tells me that it cannot find the images.

Original schema:
```javascript
  rating: {
    type: Number,
    min: 0,
    max: 5,
    denyUpdate: true,
    autoform: {
      type: 'raty',
    }
  }
```

I copied the images over to /public/raty/images and then passed ratyOptions in my schema and it picked them up and was able to find the images.

Updated schema:

```javascript
  rating: {
    type: Number,
    min: 0,
    max: 5,
    denyUpdate: true,
    autoform: {
      type: 'raty',
      ratyOptions: {
        starHalf: '/raty/images/star-half.png',
        starOff: '/raty/images/star-off.png',
        starOn: '/raty/images/star-on.png'
      }
    }
  }
```

When I navigate to http://localhost:3000/packages/andrei_autoform-raty/raty/lib/images/star-half.png I can see the image so I'm unsure why the package is unable to find them. Do you have any ideas?

**Comment by oblitum** [comment]
Just trying out the package following equivalent scheme pattern and I'm also suffering the same. I'm able to access http://localhost:3000/packages/andrei_autoform-raty/raty/lib/images/star-half.png, but there's no star to click on when using `{{> afQuickField name="rating"}}`.

**Comment by oblitum** [comment]
I've followed the approach by @clayne11 but tried the raw "/packages/andrei_autoform-raty/raty/lib/images/..." instead, also worked.
